MERGE INTO ARGOCD_CTX d
	USING (SELECT :aid AS AID FROM DUAL) s
		ON (d.EVENT_AID = s.AID)
	WHEN MATCHED THEN 
		UPDATE SET d.EVENT_DATE = SYSDATE
	WHEN NOT MATCHED THEN 
		INSERT (d.EVENT_AID, 
			d.EVENT_DATE)
	VALUES (s.AID, SYSDATE)